### ISSUE TITLE
Grasping the cube gives error

### ISSUE THREAD

**Issue by faseehahmad** [JenniferBuehler/grasp-execution-pkgs#11]
Running the following command in the tutorial
roslaunch grasp_execution test_grasp.launch object_name:=cube1 robot_namespace:=jaco
gives the following error

[simple_grasp_action_client-1] process has died [pid 21351, exit code -6, cmd /home/cogrobo/catkin_ws/devel/lib/grasp_execution/simple_grasp_action_client __name:=simple_grasp_action_client __log:=/home/cogrobo/.ros/log/a9f3d39c-4f13-11e8-918b-74c63bfadf8b/simple_grasp_action_client-1.log].
log file: /home/cogrobo/.ros/log/a9f3d39c-4f13-11e8-918b-74c63bfadf8b/simple_grasp_action_client-1*.log

and is unable to attach the cube to arm. What is the reason behind it?
I ran the tutorial with grasp_fix

**Comment by JenniferBuehler** [comment]
Thanks for reporting this. I haven't tried the test grasp in a while, the grasp files have actually changed a while ago, maybe it's related to this. I'll check up on it as soon as possible.

Are you using kinetic or indigo?

**Comment by faseehahmad** [comment]
I m using ros kinetic and gazebo 7.
And I am actually trying to implement this plugin in baxter simulation.  But, first I wanted to try out the tutorial.
I have another question. I only need to install gazebo_pkgs in the same workspace as baxters. and then I have to add grasp fix as a model plugin in baxters urdf. Right?

**Comment by faseehahmad** [comment]
Hello Jennifer, I tried the plugin with baxter robot and it worked fine. Thank you very much for your help.
One thing I noticed, I don't know if it is related to the plugin or not. In my simulation I am picking up objects made in Solid works, but somehow the gripper is unable to grasp them. Solid works models are introduced through SDF file. But if I use simple objects introduced through URDF file, the grasp plugin works perfectly fine.
I don't know if the problem is with SDF models or not but it works fine with URDF models.
Thanks again

**Comment by JenniferBuehler** [comment]
Hi, to your first question (gazebo_pkgs in baxter workspace and add the plugin to URDF): Yes :) But I guess that question has been resolved as I take it from your last post.

It shouldn't really make a difference whether the model is read from URDF or SDF, technically what happens when you use URDF is that it is first translated to SDF, because Gazebo uses SDF. Maybe the solid works models don't have collision geometries defined in the SDF file. Are you able to share one SDF as an example so I can have a look?

**Comment by faseehahmad** [comment]
Attached is the sample SDF file embedded with .dae meshes.

**Comment by JenniferBuehler** [comment]
I didn't get the attachment...
anyway one way to check that it's all good is to turn on the gazebo collision shapes. Load one of your URDF models which are working fine, and one of the SolidWorks models. Then switch on "collision" shapes in ``Gazebo -> View``, and see if there are any notable differences between the models.

**Comment by faseehahmad** [comment]
Ok I will try that.
The attachment has SDF model and also the dae file which is called from the
sdf file. I have also attached a tar file which has rest of the files like
textures and STL if you need them
Thanks

**Comment by JenniferBuehler** [comment]
Sorry for getting back to you so late, it's been busy around here :/

Any progress on this?

What I meant is that the attachment hasn't come through on github, I can't download any files here.

**Comment by faseehahmad** [comment]
Unfortunately, I couldn't. I have been working on URDF models. I have attached a link to SDF modelshttps://www.dropbox.com/sh/ynlg2bqewd827wx/AADRWu85po1M90_fb_wOLdy2a?dl=0

**Comment by JenniferBuehler** [comment]
Hi, if this is still relevant: The grasp files and the source code have been updated, please try again with the new version. If you are still having trouble, please re-open this issue.
