### ISSUE TITLE
Placing an object based on world frame after picking it up

### ISSUE THREAD

**Issue by karthikm-0** [JenniferBuehler/grasp-execution-pkgs#15]
Thanks for the great package. I am trying to figure out how to plan the place operation using your script, SimpleAutomatedGraspExecution. In particular, once an object has been grasped, I would like to plan the placement based on the world frame since the objects were originally spawned with the world frame in mind. However, when using the world frame to specify a target pose, the planAndExecuteMotion method is unable to calculate a plan. Are there any approaches you can suggest to allow planning a precise placement of the object on the table according to the world frame? Thanks!

**Comment by JenniferBuehler** [comment]
Hi, could you describe in a bit more detail why it is unable to plan? There can be several reasons with MoveIt, the most likely being that the arm can not actually reach this pose with a precision which satisfies your planning criteria, or that it is in collision with the obstacle it is currently holding (and when it is "in collision" it won't plan). Therefore you have to attach the object to the arm in Moveit, as described in [this tutorial](https://github.com/JenniferBuehler/grasp-execution-pkgs/wiki/Grasping-with-Jaco-in-Gazebo-with-MoveIt#step-8-attach-the-cube-to-robot-in-moveit-and-move-the-arm). But there are other reasons too why it could fail...

**Comment by karthikm-0** [comment]
Hi Jennifer,

Sorry for the delayed response. I was able to sort the issue by using the table coordinate frame (the extra ones you've defined in the urdf). With this frame, I could plan a place and it was successful. Thank you for your help!
