### ISSUE TITLE
Question: Automated grasping

### ISSUE THREAD

**Issue by VascoLopes** [JenniferBuehler/grasp-execution-pkgs#5]
In Automated grasping tutorial is shown a way of executing grasps that are pre-computed and saved on a file. My question is if it is possible to use my own without using GraspIt, or if needed, if there is a possible way of providing GraspIt the coordinates of the grasp that was selected in order to GraspIt generate the .msg file needed.

Thank you

**Comment by JenniferBuehler** [comment]
Yes that's possible, in [part 2 of the tutorial](https://github.com/JenniferBuehler/grasp-execution-pkgs/wiki/Automated-grasping-tutorial#part-2-grasp-from-file) you just skip step 1, or rather, replace it by your own method.

You will need to generate the .msg file yourself. It's a message of type ``manipulation_msgs::Grasp`` which is pretty standard. Your grasp planner, or whichever method you are using to set the grasp, should be able to return the result as such a message, or if not, then you should be able to easily build it yourself from the information output by your grasp planner.

Generating the .msg file has nothing to do with GraspIt, it would not make sense to give graspit coordinates or something like that. It makes more sense to generate the message separately. [This line in SimpleAutomatedGraspFromFile](https://github.com/JenniferBuehler/grasp-execution-pkgs/blob/master/grasp_execution/src/SimpleAutomatedGraspFromFile.cpp#L19) may help you. See also [this line in simple_automated_grasp_execution.cpp](https://github.com/JenniferBuehler/grasp-execution-pkgs/blob/master/grasp_execution/src/simple_automated_grasp_execution.cpp#L111) which creates the object.

**Comment by VascoLopes** [comment]
Thank you very much.
