### ISSUE TITLE
Grasp with UR

### ISSUE THREAD

**Issue by Abdo1994** [JenniferBuehler/grasp-execution-pkgs#9]
Hello

I need to use the grasp execution package to grasp an object with an UR Robot.
Is this package generic for any robot or is it only valid with Jaco Arm

Thank you

**Comment by JenniferBuehler** [comment]
This package is generic, only the tutorial is with the Jaco hand.

**Comment by ilovejie** [comment]
Hi 
I have the same target with you,I also want to use UR robot to  grasp something.But I'm really a new guy,can you tell me what have you done.Share some experience with me? thank you very much!

**Comment by JenniferBuehler** [comment]
Since there has been no more discussion here, I will close this.
Please re-open if you still have questions or issues to report.

**Comment by padhupradheep** [comment]
Hey guys! 

First I would like to give the specifications on the robot and the gripper I'm using. 
Robot: Ur10
gripper:[Shadow gripper modular]( https://www.shadowrobot.com/products/modular-grasper/)

1. I have attached the gripper with the robot and developed a moveit configuration for the same. 

2. Also, I generated a open and close poses for the gripper using moveit. 

3. After these steps, I spawn a cube, use moveit to move the robot-arm to the location of the cube. 

4. I use the moveit collision avoidance technique to visualize the pick up in Rviz. 

5. Now, when I try to grasp the object using the moveit commands, I'm not able to grasp the cube. 

Am I missing any steps?

**Comment by JenniferBuehler** [comment]
Hi,
Can you describe in a bit more detail what you mean with "not able to grasp the cube" please? Is it slipping out of the gripper in Gazebo? The grasp otherwise looks good (also in Gazebo) such that there are contacts between the gripper and cube?

**Comment by padhupradheep** [comment]
Hey Jenny,

Thanks for the swift response. 
Yes, the cube is slipping out of the gripper in Gazebo!

**Comment by JenniferBuehler** [comment]
Are you using the grasp plugin? As described in the tutorial?

**Comment by padhupradheep** [comment]
Yes, I'm using the plugin! 
```
<gazebo>
   <plugin name="gazebo_grasp_fix" filename="libgazebo_grasp_fix.so">
        <arm>
           <arm_name>arm</arm_name>
           <palm_link> wrist_3_link  </palm_link>
           <gripper_link>H1_F1_link_1</gripper_link>
           <gripper_link>H1_F2_link_1</gripper_link>
           <gripper_link>H1_F3_link_1</gripper_link>
           <gripper_link>H1_F1_link_2</gripper_link>
           <gripper_link>H1_F2_link_2</gripper_link>
           <gripper_link>H1_F3_link_2</gripper_link>
       </arm>
       <forces_angle_tolerance>100</forces_angle_tolerance>
       <update_rate>4</update_rate>
       <grip_count_threshold>4</grip_count_threshold>
       <max_grip_count>20</max_grip_count>
       <release_tolerance>0.005</release_tolerance>
       <disable_collisions_on_attach>false</disable_collisions_on_attach>
       <contact_topic>__default_topic__</contact_topic>
    </plugin>
</gazebo>
```

**Comment by padhupradheep** [comment]
Hey, 
Now its working! 

I actually misunderstood this point from your wiki

> There should be no other movable joints between the palm link and the gripper joints

I just made the other joints in between the palm and the F2_link_2 fixed. 

Sorry for the disturbance

**Comment by JenniferBuehler** [comment]
Hi, sorry for the late response. I see it's resolved now, glad it's working now!

**Comment by Amanullah08072** [comment]
Hi
I am getting this error 
can Someone help me out

[ INFO] [1649594466.334587980, 0.157000000]: Loaded gazebo_ros_control.
[Msg] Loading grasp-fix plugin
[Msg] GazeboGraspFix: Using disable_collisions_on_attach 0
[Msg] GazeboGraspFix: Using update rate 4
[Msg] GazeboGraspFix: Using max_grip_count 8
[Msg] GazeboGraspFix: Using grip_count_threshold 4
[Msg] GazeboGraspFix: Using release_tolerance 0.005
Error [Element.cc:914] Missing element description for [palm_link]
[Err] [GazeboGraspFix.cpp:202] ERROR: GazeboGraspFix: Cannot use a GazeboGraspFix arm because not all of <arm_name>, <palm_link> and <gripper_link> elements specified in URDF/SDF. Skipping.
[Err] [GazeboGraspFix.cpp:261] ERROR: GazeboGraspFix: Cannot use a GazeboGraspFix because no arms were configured successfully. Plugin will not work.
